# Generated by Django 3.1.1 on 2023-04-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(help_text='Employee ID', max_length=5, primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
